bloccitoff/config/routes.rb
Bloccitoff::Application.routes.draw do

  resources :todos  
  devise_for :users
  root 'welcome#index'

  
    
 

    

  

end

bloccitoff/app/models/todo.rb
class Todo < ActiveRecord::Base
	belongs_to :user
end

bloccitoff/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todos


end

bloccitoff/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    '/todos#index'
  end
end

bloccitoff/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    Rails.logger.info ">>>>>>>>>>>>> in todos controller"
    @todos = current_user.todos
    Rails.logger.info ">>>>>>>>>>>>>> #{@todos.inspect}"
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user = current_user
    if @todo.save
      flash[:notice] = "Your todo has been created."
    else
      flash[:error] = "There was an error saving your todo. Please try again."
    end 
    redirect_to todos_path
  end

  # def edit
  #   @todo = current_user.todos.find_by_id(params[:id])
  # end

  def update
    @todo = current_user.todos.find_by_id(params[:id])
    if @quick_fact.update_attributes(params[:id])
      flash[:notice] = 'Todo was successfully updated.'
      redirect_to todos_path
    else
      render :action => "index", :id => params[:id]
    end
  end

  def destroy
    @todo = current_user.todos.find_by_id(params[:id])
    @todo.destroy
    redirect_to todos_path
  end

  private

  def todo_params
    params.require(:todo).permit(:description, :complete)
  end
end

bloccitoff/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if current_user 
  		redirect_to todos_path
  	end
  end
end

bloccitoff/app/helpers/application_helper.rb
module ApplicationHelper
end

bloccitoff/app/helpers/todos_helper.rb
module TodosHelper
end

bloccitoff/app/helpers/welcome_helper.rb
module WelcomeHelper
end

bloccitoff/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccitoff</title>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <body>
    <div class="container">
    	
   <div class="pull-right user-info">
     <% if current_user %>
       Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
     <% else %>
       <%= link_to "Sign In", new_user_session_path %> or 
       <%= link_to "Sign Up", new_user_registration_path %>
     <% end %>
   </div> 

<%= yield %>

</body>
</html>

bloccitoff/app/views/todos/destroy.html.erb
<h1>Todos#destroy</h1>
<p>Find me in app/views/todos/destroy.html.erb</p>

bloccitoff/app/views/todos/edit.html.erb
<h1>Todos#edit</h1>
<p>Find me in app/views/todos/edit.html.erb</p>

bloccitoff/app/views/todos/index.html.erb
<div>
	<p>
	  Your to-do list is here!
	</p>
</div>

<h1>Todos</h1>

<table class="table table-striped">
 <thead>
   	<tr>
    	<th>Description</th>
    	<th>Days left</th>
    	<th>Complete</th>
   	</tr>
	</thead>  
  <tbody>
    <% @todos.each do |todo| %>
  	<tr>
    	<td><%= todo.description %></td>
    	<td><%= distance_of_time_in_words_to_now(todo.created_at + 7.days) %></td>
      <td>
        <div input id="ck-button"> 
          <%= button_to "Complete", todo_path(todo), action: :delete, method: :delete, id: todo.id %>
        </div>
      </td>
  	</tr>
     <% end %>
     <tr>
      <td>
        <%= form_for Todo.new do |f| %>
        <%= f.text_field :description %>
        <%= f.submit "Save" %>
        <% end %>
      </td>
      <td></td>
      <td></td>
    </tr>
  </tbody> 
</table>

    
 
<!-- <p><%= link_to "New todo", new_todo_path, class: "btn btn-success" %></p>
 -->

bloccitoff/app/views/todos/new.html.erb
<!-- Todo - put this into index -->

bloccitoff/app/views/todos/show.html.erb
<h1>Todos#show</h1>
<p>Find me in app/views/todos/show.html.erb</p>

bloccitoff/app/views/welcome/index.html.erb
<h1>Bloccitoff</h1>
<p>A self-destructing to-do list to keep you focused on the things that really matter.</p>